apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: testing-relationships
  description: Hackathon testing of different component types
spec:
  type: url
  targets:
    - ./components/fedex-service-api.yaml
    - ./apis/local-definition.yaml
    - ./apis/from-swagger-json.yaml
    - ./apis/from-web-yaml.yaml
    - ./groups/gold-team.yaml
