apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics-ui
  description: Helps institutions create the highests probability of enrollment success
  title: Analytics UI
  tags:
    - react
  links:
    - url: https://github.com/parchment-io/analytics-ui
      title: Github
  annotations:
    github.com/project-slug: parchment-io/analytics-ui
spec:
  type: website
  system: value-stream-analyze
  lifecycle: production
  owner: gold-team
  consumesApis:
    - analytics-engine-api
    - learner-service-api
    - parchment-identity-provider
    - member-directory-api
  dependsOn:
    - component:analytics-engine-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics-engine-api
  description: Backend for Analytics UI
  title: Analytics Engine API
  tags:
    - java
  links:
    - url: https://github.com/parchment-io/analytics-engine-api
      title: Github
    - url: https://structurizr.com/workspace/69193/diagrams#analyze
      title: Structurizr
  annotations:
    'backstage.io/kubernetes-label-selector': 'parchment.app=analytics-engine-api'
    github.com/project-slug: parchment-io/analytics-engine-api
    backstage.io/techdocs-ref: url:https://github.com/backstage/backstage/blob/master/mkdocs.yml
spec:
  type: service
  system: value-stream-analyze
  lifecycle: production
  owner: gold-team
  providesApis:
    - analytics-engine-api
  dependsOn:
    - resource:analyze-db
    - resource:analyze-neo4j
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: analytics-engine-api
  description: API for Analytics Engine
  tags:
    - java
  links:
    - url: https://qa-apis.us-west-2.aws.parchment.com/analytics-engine-api/v1/
      title: Swagger QA
spec:
  type: openapi
  system: value-stream-analyze
  lifecycle: production
  owner: gold-team
  definition:
    $text: https://qa-apis.us-west-2.aws.parchment.com/fedex-service-api/v3/api-docs?group=app-v1
# todo fix when url works again    $text: https://qa-apis.us-west-2.aws.parchment.com/analytics-engine-api/v1/api-docs?group=app-v1
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: analyze-db
  description: Primary Database for Analyze
  tags:
    - postgresql
spec:
  type: database
  owner: gold-team
  system: value-stream-analyze
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: analyze-neo4j
  description: A graph database management system
  tags:
    - java
spec:
  type: database
  owner: gold-team
  system: value-stream-analyze
---
#- parchment-identity-provider
#- member-directory-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: learner-service-api
  description: API for Learner Service
  tags:
    - java
  links:
    - url: https://qa-apis.us-west-2.aws.parchment.com/learner-service-api/swagger-ui/
      title: Swagger QA
spec:
  type: openapi
  system: value-stream-analyze
  lifecycle: production
  owner: gold-team
  definition:
    $text: https://qa-apis.us-west-2.aws.parchment.com/learner-service-api/v3/api-docs?group=app-v1
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: learner-service
  description: Learner Service
  title: Learner Service
  tags:
    - java
  links:
    - url: https://github.com/parchment-io/learner-service-api
      title: Github
    - url: https://structurizr.com/workspace/69193/diagrams#Learner-Service-API
      title: Structurizr
  annotations:
    'backstage.io/kubernetes-label-selector': 'parchment.app=learner-service-api'
    github.com/project-slug: parchment-io/learner-service-api
spec:
  type: service
  system: value-stream-analyze
  lifecycle: production
  owner: gold-team
  providesApis:
    - learner-service-api
  dependsOn:
    - resource:external-kong
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: external-kong
  description: API Authentication System
  tags:
    - kong
spec:
  type: service
  owner: gold-team
  system: value-stream-analyze