apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: gold-team
  description: The Gold Team - responsible for Infrastructure
spec:
  type: team
  profile:
    displayName: Gold Team
    picture: https://github.com/marcsumus/backstage-testing/tree/main/groups/images/gold-team.jpg
  parent: application-engineering
  children: []
  members: [marcsumus]
