apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: marcsumus
spec:
  profile:
    displayName: Mark Bonges
    email: mark.bonges@parchment.com
    picture: https://github.com/marcsumus/backstage-testing/tree/main/groups/images/Avengers-Captain-America-icon.jpg
  memberOf: [gold-team]
