apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: from-swagger-json
  description: Testing loading open API from swagger open api json
  tags:
    - java
    - testing
  links:
    - url: https://www.fedex.com/en-us/developer/web-services.html
      title: FedEx Web Services Developer Portal
      icon: local_shipping
    - url: https://qa-apis.us-west-2.aws.parchment.com/fedex-service-api/swagger-ui/
      title: Swagger QA
spec:
  type: openapi
  system: delivery
  lifecycle: production
  owner: gold-team
  definition:
    $json: from-swagger-json-openapi.json
