apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: from-web-yaml
  description: loading api from web yaml
  tags:
    - spotify
    - rest
spec:
  type: openapi
  lifecycle: production
  owner: gold-team
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/spotify.com/2021.4.2/openapi.yaml
